version: "3"
services:
  nginx:
    image: nginx-simple:latest
    container_name: nginx-simple
    restart: always
    network_mode: "bridge"
    expose:
      - "4100"
    environment:
      VIRTUAL_HOST: magmaplate.com,www.magmaplate.com
    ports:
      - "4100:80"
    volumes:
      - ./:/var/www/
    build:
      context: .

#networks:
  #default:
   # external:
     # name: internal_net_1
